import { useEffect, useMemo, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import {
  FacebookShareButton,
  FacebookIcon,
  PinterestShareButton,
  PinterestIcon,
  RedditShareButton,
  RedditIcon,
  WhatsappShareButton,
  WhatsappIcon,
  LinkedinShareButton,
  LinkedinIcon,
} from 'next-share';

const formatCurrency = (value) => {
  const numberValue = Number.isFinite(value) ? value : 0;
  return new Intl.NumberFormat('en-NA', {
    style: 'currency',
    currency: 'NAD',
    minimumFractionDigits: 2,
  }).format(numberValue);
};

const parseAmount = (value) => {
  const parsed = parseFloat(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

const calculateTax2025 = (annualIncome) => {
  if (annualIncome <= 100000) {
    return 0;
  }
  if (annualIncome <= 150000) {
    return (annualIncome - 100000) * 0.18;
  }
  if (annualIncome <= 350000) {
    return (annualIncome - 150000) * 0.25 + 9000;
  }
  if (annualIncome <= 550000) {
    return (annualIncome - 350000) * 0.28 + 59000;
  }
  if (annualIncome <= 850000) {
    return (annualIncome - 550000) * 0.3 + 115000;
  }
  if (annualIncome <= 1550000) {
    return (annualIncome - 850000) * 0.32 + 205000;
  }
  return (annualIncome - 1550000) * 0.37 + 429000;
};

const calculateTax2023 = (annualIncome) => {
  if (annualIncome <= 50000) {
    return 0;
  }
  if (annualIncome <= 100000) {
    return (annualIncome - 50000) * 0.18;
  }
  if (annualIncome <= 300000) {
    return (annualIncome - 100000) * 0.25 + 9000;
  }
  if (annualIncome <= 500000) {
    return (annualIncome - 300000) * 0.28 + 59000;
  }
  if (annualIncome <= 800000) {
    return (annualIncome - 500000) * 0.3 + 115000;
  }
  if (annualIncome <= 1500000) {
    return (annualIncome - 800000) * 0.32 + 205000;
  }
  return (annualIncome - 1500000) * 0.37 + 429000;
};

const buildBreakdown = (annualTax) => ({
  annual: formatCurrency(annualTax),
  biannual: formatCurrency(annualTax / 2),
  quarterly: formatCurrency(annualTax / 4),
  monthly: formatCurrency(annualTax / 12),
});

export default function Home() {
  const [amount, setAmount] = useState(0);
  const [carCost, setCarCost] = useState('');
  const [housingAllowance, setHousingAllowance] = useState('');
  const [businessProfit, setBusinessProfit] = useState('');
  const [businessTurnover, setBusinessTurnover] = useState('');
  const [viewMode, setViewMode] = useState('individual');

  useEffect(() => {
    const handleWheel = (event) => {
      if (event.target.type === 'range') {
        event.preventDefault();
      }
    };

    document.body.addEventListener('wheel', handleWheel, { passive: false });

    return () => {
      document.body.removeEventListener('wheel', handleWheel);
    };
  }, []);

  const handleSliderChange = (event) => {
    setAmount(Number(event.target.value));
  };

  const handleReset = () => {
    setAmount(0);
    setCarCost('');
    setHousingAllowance('');
  };

  const handleSliderWheel = (event) => {
    const currentValue = parseAmount(amount);
    const newValue = currentValue + (event.deltaY > 0 ? -1000 : 1000);

    if (newValue >= 0 && newValue <= 250000) {
      setAmount(newValue);
    }
  };

  const shareUrl = 'https://namfreetaxcalc.vercel.app';

  const today = new Date();
  const year = today.getFullYear();
  const lastUpdatedDisplay = today.toLocaleDateString('en-NA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const lastUpdatedIso = today.toISOString().split('T')[0];

  const monthlySalary = parseAmount(amount);
  const annualBaseSalary = monthlySalary * 12;
  const carCostValue = parseAmount(carCost);
  const housingAllowanceValue = parseAmount(housingAllowance);
  const carBenefitMonthly = carCostValue * 0.015;
  const taxableMonthlyIncome = monthlySalary + carBenefitMonthly + housingAllowanceValue;
  const taxableAnnualIncome = taxableMonthlyIncome * 12;

  const newAnnualTax = calculateTax2025(taxableAnnualIncome);
  const oldAnnualTax = calculateTax2023(taxableAnnualIncome);
  const newBreakdown = buildBreakdown(newAnnualTax);
  const oldBreakdown = buildBreakdown(oldAnnualTax);
  const taxSavings = oldAnnualTax - newAnnualTax;

  const sscEmployee = Math.min(taxableMonthlyIncome * 0.009, 99);
  const sscEmployer = Math.min(taxableMonthlyIncome * 0.009, 99);

  const whatsappMessage = useMemo(() => {
    return [
      'Namibia Tax Calculator 2025/26 Summary',
      `Monthly Salary: ${formatCurrency(monthlySalary)}`,
      `Taxable Annual Income: ${formatCurrency(taxableAnnualIncome)}`,
      `New Annual Tax (2025/26): ${formatCurrency(newAnnualTax)}`,
      `Old Annual Tax (2023): ${formatCurrency(oldAnnualTax)}`,
      `Estimated Savings: ${formatCurrency(taxSavings)}`,
      'Generated by NamFreeTaxCalc',
    ].join('\n');
  }, [monthlySalary, taxableAnnualIncome, newAnnualTax, oldAnnualTax, taxSavings]);

  const whatsappLink = `https://wa.me/?text=${encodeURIComponent(whatsappMessage)}`;

  const corporateProfitValue = parseAmount(businessProfit);
  const corporateTurnoverValue = parseAmount(businessTurnover);
  const corporateTax = corporateProfitValue * 0.3;
  const vatRequired = corporateTurnoverValue >= 1000000;

  const handlePrint = () => {
    if (typeof window !== 'undefined') {
      window.print();
    }
  };

  return (
    <>
      <Head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@graph': [
                {
                  '@type': 'SoftwareApplication',
                  name: 'Namibia Tax Calculator 2025/26',
                  applicationCategory: 'FinanceApplication',
                  operatingSystem: 'Web',
                  offers: {
                    '@type': 'Offer',
                    price: '0',
                    priceCurrency: 'NAD',
                  },
                  featureList: 'PAYE Calculation, SSC Calculation, Corporate Tax',
                  dateModified: lastUpdatedIso,
                  targetCountry: 'NA',
                  url: 'https://namfreetaxcalc.vercel.app',
                },
                {
                  '@type': 'FAQPage',
                  mainEntity: [
                    {
                      '@type': 'Question',
                      name: 'What is the tax threshold in Namibia for 2025?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'For the 2025/2026 tax year, the tax-free threshold for individuals in Namibia is N$100,000 per year.',
                      },
                    },
                    {
                      '@type': 'Question',
                      name: 'How much is the Social Security Commission (SSC) deduction?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'The SSC deduction is 0.9% of monthly taxable income for employees, capped at N$99 per month.',
                      },
                    },
                    {
                      '@type': 'Question',
                      name: 'What is the corporate tax rate in Namibia?',
                      acceptedAnswer: {
                        '@type': 'Answer',
                        text: 'Effective January 1, 2025, the corporate tax rate for non-mining companies in Namibia is 30%.',
                      },
                    },
                  ],
                },
              ],
            }),
          }}
        />
      </Head>
      <main className="con dflex shadow1">
        <div className="mxauto mb3 p2 content">
            <div className="dflex p2">
              <Image width={100} height={65} src="/flag.png" alt="Namibian Flag" className="mxauto shadow1" />
            </div>
            <h1 className="txtbold h4 txtfont2 txtcenter">Namibia Tax Calculator 2025/26</h1>
            <p className="h5 txtfont1 txtcenter">Calculate your monthly salary or business tax estimate.</p>
            <p className="txtcenter txtfont1">
              Last updated: {lastUpdatedDisplay} · Reviewed by Ciesto Media &amp; Design
            </p>
            <div className="toggle-group">
              <button
                type="button"
                className={`toggle-button ${viewMode === 'individual' ? 'toggle-active' : ''}`}
                onClick={() => setViewMode('individual')}
              >
                Individual
              </button>
              <button
                type="button"
                className={`toggle-button ${viewMode === 'business' ? 'toggle-active' : ''}`}
                onClick={() => setViewMode('business')}
              >
                Business
              </button>
            </div>

            {viewMode === 'individual' ? (
              <>
                <section className="section" aria-labelledby="monthly-salary-heading">
                  <h2 className="section-title" id="monthly-salary-heading">
                    Monthly Salary (N$)
                  </h2>
                  <div className="dflex">
                    <input
                      id="monthly-salary-input"
                      type="number"
                      step="500"
                      name="amount"
                      value={amount}
                      onChange={(event) => setAmount(event.target.value)}
                      className="border border1 bordercol1 mr1 p2 mxauto txtcenter txtfont2"
                      min="0"
                      aria-label="Monthly salary amount"
                    />
                  </div>
                  <div className="dflex">
                    <input
                      id="monthly-salary-range"
                      type="range"
                      min="0"
                      max="250000"
                      step="50"
                      value={amount}
                      onChange={handleSliderChange}
                      onWheel={handleSliderWheel}
                      className="border border1 bordercol1 mr1 p2 mxauto txtcenter txtfont2"
                      aria-label="Monthly salary slider"
                    />
                  </div>
                </section>

                <section className="section card" aria-labelledby="fringe-benefits-heading">
                  <h2 className="section-title" id="fringe-benefits-heading">
                    Fringe Benefit Calculator (Namibian)
                  </h2>
                  <p className="section-subtitle">Company Car (1.5% of cost price) & Housing Allowance</p>
                  <div className="grid">
                    <label className="field" htmlFor="company-car-cost">
                      Company Car Cost Price (N$)
                      <input
                        id="company-car-cost"
                        type="number"
                        value={carCost}
                        onChange={(event) => setCarCost(event.target.value)}
                        className="border border1 bordercol1 p2 txtcenter txtfont2"
                        min="0"
                      />
                    </label>
                    <label className="field" htmlFor="housing-allowance">
                      Housing Allowance (Monthly N$)
                      <input
                        id="housing-allowance"
                        type="number"
                        value={housingAllowance}
                        onChange={(event) => setHousingAllowance(event.target.value)}
                        className="border border1 bordercol1 p2 txtcenter txtfont2"
                        min="0"
                      />
                    </label>
                  </div>
                  <div className="summary">
                    <p>Company Car Benefit (Monthly): {formatCurrency(carBenefitMonthly)}</p>
                    <p>Housing Allowance (Monthly): {formatCurrency(housingAllowanceValue)}</p>
                    <p className="txtbold">Taxable Monthly Income (incl. benefits): {formatCurrency(taxableMonthlyIncome)}</p>
                  </div>
                </section>

                <div className="result-container txtfont2">
                  <p className="txtcenter">Annual Base Salary: {formatCurrency(annualBaseSalary)}</p>
                  <p className="txtcenter">Taxable Annual Income (incl. benefits): {formatCurrency(taxableAnnualIncome)}</p>
                  <p className="txtbold txtcenter">Annual Tax Payable (2025/26): {newBreakdown.annual}</p>
                  <p className="txtcenter">Bi-Annual Tax Payable: {newBreakdown.biannual}</p>
                  <p className="txtcenter">Quarterly Tax Payable: {newBreakdown.quarterly}</p>
                  <p className="txtcenter">Monthly Tax Payable: {newBreakdown.monthly}</p>
                </div>

                <section className="section card" aria-labelledby="comparison-heading">
                  <h2 className="section-title" id="comparison-heading">
                    Side-by-Side Comparison
                  </h2>
                  <div className="comparison">
                    <div>
                      <p className="txtbold">Old Tax (2023)</p>
                      <p>Annual: {oldBreakdown.annual}</p>
                      <p>Monthly: {oldBreakdown.monthly}</p>
                    </div>
                    <div>
                      <p className="txtbold">New Tax (2025/26)</p>
                      <p>Annual: {newBreakdown.annual}</p>
                      <p>Monthly: {newBreakdown.monthly}</p>
                    </div>
                    <div>
                      <p className="txtbold">Estimated Savings</p>
                      <p>Annual: {formatCurrency(taxSavings)}</p>
                      <p>Monthly: {formatCurrency(taxSavings / 12)}</p>
                    </div>
                  </div>
                </section>

                <section className="section card" aria-labelledby="ssc-heading">
                  <h2 className="section-title" id="ssc-heading">
                    Social Security (SSC)
                  </h2>
                  <p>Employee Contribution (0.9%, capped at N$99): {formatCurrency(sscEmployee)}</p>
                  <p>Employer Contribution (0.9%, capped at N$99): {formatCurrency(sscEmployer)}</p>
                </section>

                <section className="section actions" aria-label="Download or share results">
                  <button type="button" className="action-button" onClick={handlePrint}>
                    Download Salary Breakdown (PDF)
                  </button>
                  <a className="action-button secondary" href={whatsappLink} target="_blank" rel="noreferrer">
                    Share to WhatsApp
                  </a>
                </section>

                <div className="dflex pb3">
                  <Image
                    width={35}
                    height={35}
                    src="/rotate-right-solid.png"
                    alt="Reset Button"
                    className="mxauto mt3 fillblue"
                    onClick={handleReset}
                  />
                </div>
              </>
            ) : (
              <>
                <section className="section card" aria-labelledby="corporate-tax-heading">
                  <h2 className="section-title" id="corporate-tax-heading">
                    Corporate Tax & VAT Calculator
                  </h2>
                  <p className="section-subtitle">Non-mining corporate tax rate: 30% (2025)</p>
                  <div className="grid">
                    <label className="field" htmlFor="business-profit">
                      Annual Taxable Profit (N$)
                      <input
                        id="business-profit"
                        type="number"
                        value={businessProfit}
                        onChange={(event) => setBusinessProfit(event.target.value)}
                        className="border border1 bordercol1 p2 txtcenter txtfont2"
                        min="0"
                      />
                    </label>
                    <label className="field" htmlFor="business-turnover">
                      Annual Turnover (N$)
                      <input
                        id="business-turnover"
                        type="number"
                        value={businessTurnover}
                        onChange={(event) => setBusinessTurnover(event.target.value)}
                        className="border border1 bordercol1 p2 txtcenter txtfont2"
                        min="0"
                      />
                    </label>
                  </div>
                  <div className="summary">
                    <p className="txtbold">Corporate Tax Payable: {formatCurrency(corporateTax)}</p>
                    <p>VAT Registration Threshold: {formatCurrency(1000000)}</p>
                    <p className={vatRequired ? 'status-good' : 'status-muted'}>
                      {vatRequired
                        ? 'VAT registration required based on turnover.'
                        : 'VAT registration not yet required based on turnover.'}
                    </p>
                  </div>
                </section>
              </>
            )}

            <hr />
            <section className="txtcenter txtfont2 p3" aria-labelledby="tax-brackets-heading">
              <p className="pb3">
                Introducing the Namibia Tax Calculator 2025/26. Quickly estimate PAYE, fringe benefits, and business tax
                obligations using the latest Namibian tax thresholds from the PwC Tax Reference Card.
              </p>
              <h2 className="txtbold pb3" id="tax-brackets-heading">
                2025/26 Individual Income Tax Brackets
              </h2>
              <table className="tax-table">
                <caption className="txtbold pb3">Namibia 2025/26 PAYE brackets</caption>
                <thead>
                  <tr>
                    <th scope="col">Annual taxable income (N$)</th>
                    <th scope="col">Tax rate</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>N$ 0 - 100 000</td>
                    <td>0% (Tax free threshold)</td>
                  </tr>
                  <tr>
                    <td>N$ 100 001 - 150 000</td>
                    <td>18% of amount over N$ 100 000</td>
                  </tr>
                  <tr>
                    <td>N$ 150 001 - 350 000</td>
                    <td>N$ 9 000 + 25% of amount over N$ 150 000</td>
                  </tr>
                  <tr>
                    <td>N$ 350 001 - 550 000</td>
                    <td>N$ 59 000 + 28% of amount over N$ 350 000</td>
                  </tr>
                  <tr>
                    <td>N$ 550 001 - 850 000</td>
                    <td>N$ 115 000 + 30% of amount over N$ 550 000</td>
                  </tr>
                  <tr>
                    <td>N$ 850 001 - 1 550 000</td>
                    <td>N$ 205 000 + 32% of amount over N$ 850 000</td>
                  </tr>
                  <tr>
                    <td>Above N$ 1 550 000</td>
                    <td>N$ 429 000 + 37% of amount over N$ 1 550 000</td>
                  </tr>
                </tbody>
              </table>
              <h3 className="txtbold pb3 mt3">Business Updates</h3>
              <ul className="calendar">
                <li>Corporate tax for non-mining companies: 30% (from 1 Jan 2025)</li>
                <li>VAT registration threshold: N$ 1 000 000 annual turnover</li>
              </ul>
            </section>

            <section className="section card" aria-labelledby="tax-calendar-heading">
              <h2 className="section-title" id="tax-calendar-heading">
                NamRA Tax Calendar Notifications
              </h2>
              <ul className="calendar">
                <li>30 June: Individual income tax return deadline.</li>
                <li>Monthly (20th): PAYE remittance to NamRA.</li>
                <li>Bi-monthly (last day): VAT return submission for registered vendors.</li>
              </ul>
            </section>

            <section className="section card" aria-labelledby="namra-links-heading">
              <h2 className="section-title" id="namra-links-heading">
                NamRA Integration Links
              </h2>
              <p>
                File directly on the{' '}
                <a href="https://itas.mof.gov.na" target="_blank" rel="noreferrer">
                  NamRA ITAS portal
                </a>{' '}
                or read the{' '}
                <a
                  href="https://itas.mof.gov.na/Account/Register"
                  target="_blank"
                  rel="noreferrer"
                >
                  ITAS registration guide
                </a>
                .
              </p>
            </section>
        </div>
      </main>
      <div className="con2">
        <footer className="con footer">
          <div className="dflex">
            <div className=" txtcenter mxauto">
              <p className=" txtbold txtfont2">Share</p>
              <FacebookShareButton url={shareUrl}>
                <FacebookIcon size={32} round />
              </FacebookShareButton>
              <PinterestShareButton url={shareUrl}>
                <PinterestIcon size={32} round />
              </PinterestShareButton>
              <RedditShareButton url={shareUrl}>
                <RedditIcon size={32} round />
              </RedditShareButton>
              <WhatsappShareButton url={shareUrl}>
                <WhatsappIcon size={32} round />
              </WhatsappShareButton>
              <LinkedinShareButton url={shareUrl}>
                <LinkedinIcon size={32} round />
              </LinkedinShareButton>
            </div>
          </div>
          <div className="txtcenter txtfont2">
            <p className="footer-disclaimer">
              Based on the 2025 PwC Tax Rate Card. Consult a professional for official filing.{' '}
              <a
                href="https://www.namra.org.na/tax/"
                target="_blank"
                rel="nofollow external noreferrer"
              >
                NamRA official tax resources
              </a>
              .
            </p>
            <span className="txtfont1">
              &#169; {year} <a href="https://www.facebook.com/ciestomedia" target="_blank" rel="noreferrer">CiestoMedia</a>
            </span>
          </div>
        </footer>
      </div>
    </>
  );
}
